name: test

on: [ push ]

jobs:
  test:
    check-bats-version:
      runs-on: ubuntu-latest # где запускаем
      steps:
        - uses: actions/checkout@v4 # выкачиваем репозиторий
        - uses: actions/setup-java@v4 # настраиваем Java
          with:
            distribution: 'zulu'
            java-version: '21'
        - run: ./gradlew clean test # запускаем тесты